# Generated by Django 3.2.17 on 2023-02-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='director',
            new_name='_director',
        ),
    ]
