# Generated by Django 3.2.17 on 2023-02-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_director_video__director'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='has_manual_views',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='manual_views',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
