# Generated by Django 3.2.17 on 2023-02-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_video_manual_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
