# Generated by Django 3.2.17 on 2023-03-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_video_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='born',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='cast_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='education',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='born',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='cast_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='education',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
